export default {
  login: "jlengstorf",
  id: 163561,
  node_id: "MDQ6VXNlcjE2MzU2MQ==",
  avatar_url: "https://avatars.githubusercontent.com/u/163561?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/jlengstorf",
  html_url: "https://github.com/jlengstorf",
  followers_url: "https://api.github.com/users/jlengstorf/followers",
  following_url:
    "https://api.github.com/users/jlengstorf/following{/other_user}",
  gists_url: "https://api.github.com/users/jlengstorf/gists{/gist_id}",
  starred_url: "https://api.github.com/users/jlengstorf/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/jlengstorf/subscriptions",
  organizations_url: "https://api.github.com/users/jlengstorf/orgs",
  repos_url: "https://api.github.com/users/jlengstorf/repos",
  events_url: "https://api.github.com/users/jlengstorf/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/jlengstorf/received_events",
  type: "User",
  site_admin: false,
  name: "Jason Lengstorf",
  company: "@netlify ",
  blog: "https://learnwithjason.dev",
  location: "Portland, Oregon",
  email: null,
  hireable: null,
  bio: "💻 Developer / software architect.\r\n📢 Frequent speaker.        \r\n🎨 Occasional designer.\r\n🍸 Mediocre bartender.",
  twitter_username: "jlengstorf",
  public_repos: 442,
  public_gists: 81,
  followers: 3470,
  following: 5,
  created_at: "2009-12-07T04:12:57Z",
  updated_at: "2022-01-02T23:32:19Z",
};
